[build-system]
requires = ["setuptools>=64.4.0", "wheel", "pip>=24.0"]
build-backend = "setuptools.build_meta"

[project]
name = "laspated"
version = "0.0.9"
requires-python = ">= 3.10"
readme = { file = "README.md", content-type = "text/markdown" }
description = "Analysis of Spatio-temporal data"
license = { file = "LICENSE.txt" }
dependencies = [
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "geopandas>=0.12.2",
    "fiona>=1.9.6",
    "matplotlib>=3.10.9",
    "h3>=4.5.0",
    "rtree>=1.4.1",
    "descartes>=1.1.0",
]
authors = [
    { name = "Vincent Guigues" },
    { name = "Anton Kleywegt" },
    { name = "Giovanni Amorim" },
    { name = "André Mazal" },
    { name = "Victor Nascimento" },
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]


# [project.optional-dependencies]
# dev = [
#     "pdbpp",
#     "bump-my-version",
#     "pre-commit",
# ]
# docs = [
#     "jupyter-book",
#     "jupytext",
#     "sphinxcontrib-bibtex",
# ]

[tool.setuptools.packages.find]
where = ["src"]
include = ["laspated"]
